    ResultException(Exception cause) {
      super(cause);
    }

